// Experience page — project data
// ─────────────────────────────────────────────────
// Two sets: FEATURED (6 flagship case studies) + ARCHIVE
// (selected supplementary projects). Shared shape so the
// DetailModal can render either type.
//
// Client and agency are split into separate fields so the meta
// row can label them distinctly.

const DISCIPLINES = [
  'Live',
  'Immersive',
  'IP Development',
  'Technology',
  'Public Event',
  'Public Realm',
  'Sport',
  'Culture',
  'Commercial Strategy',
];

const FEATURED = [
  {
    id: 'human',
    title: 'HUMAN — Festival of Immersive Storytelling',
    label: 'IP Platform Development',
    projectType: 'Platform Strategy & IP Development',
    year: '2019 — 2020',
    role: 'Strategic Advisory · Commercial Modelling · Platform Development',
    client: 'London & Partners',
    agency: 'The nvisible Agency',
    tagline: 'A proposed international IP platform for immersive storytelling — originated, structured and developed with London & Partners.',
    outcome: 'HUMAN explored a scalable international platform for immersive storytelling, combining cultural programming, live experience and commercial IP strategy. The work led to a joint venture between The nvisible Agency and London & Partners, approved by the Mayor of London.',
    scope: [
      'IP & platform development',
      'Commercial modelling',
      'Audience strategy',
      'Experience positioning',
      'Partnership structuring',
      'Investor materials',
      'Development advisory',
    ],
    body: [
      'The project explored how London could originate and operate a scalable international platform for immersive culture, bringing together artists, technologists and audience experiences around the theme of humanity. The work spanned IP positioning, commercial structuring, audience modelling and partnership development.',
      'It led to the formation of a joint venture between The nvisible Agency and London & Partners, approved by the Mayor of London, to develop and operate the platform internationally. Although paused due to the Covid pandemic, HUMAN remains a significant example of strategic IP development and platform-led immersive infrastructure planning.',
    ],
    disciplines: ['IP Development', 'Immersive', 'Culture', 'Commercial Strategy'],
    tags: ['IP Development', 'Platform Strategy', 'Commercial Modelling', 'Strategic Advisory', 'Audience Strategy', 'Partnership Structuring', 'Investor Materials', 'Immersive Culture'],
    images: [
      { src: 'assets/experience/human-billboard.jpg', tone: 'dark' },
      { src: 'assets/experience/human-abudhabi-flags.jpg', tone: 'dark' },
      { src: 'assets/experience/human-poster-cities.jpg', tone: 'dark' },
      { src: 'assets/experience/human-poster-dancer.png', tone: 'dark' },
      { src: 'assets/experience/human-poster-laser.jpg', tone: 'dark' },
      { src: 'assets/experience/human-poster-cube.jpg', tone: 'dark' },
      { src: 'assets/experience/human-framework.jpg', tone: 'dark' },
      { src: 'assets/experience/human-cities.jpg', tone: 'dark' },
    ],
  },
  {
    id: 'moir',
    title: 'Museum of Infinite Realities',
    label: 'IP Platform Development',
    projectType: 'Strategic Advisory & Development Structuring',
    year: '2022 — 2024',
    role: 'Strategic Advisory · Commercial Modelling · Development Structuring',
    client: 'MOIR',
    agency: null,
    tagline: 'Strategic and commercial foundations for an immersive museum.',
    outcome: 'Museum of Infinite Realities focused on the strategic and commercial foundations for an immersive cultural platform combining digital art, technology and location-based experience — handed over to the delivery team for production.',
    scope: [
      'IP & platform development',
      'Commercial modelling',
      'Audience positioning',
      'Operating model design',
      'Development pathways',
      'Project structuring',
    ],
    body: [
      'Strategic advisory, commercial modelling and early-stage development support for the Museum of Infinite Realities — an immersive cultural platform exploring new forms of digital exhibition and audience experience.',
      'The work focused on shaping the commercial and strategic foundations of the project, including audience positioning, operating model considerations, development pathways and initial project structuring.',
      'Following the initial advisory and development phase, the project was handed over to the delivery team for production and implementation.',
    ],
    disciplines: ['IP Development', 'Immersive', 'Culture', 'Commercial Strategy'],
    tags: ['IP Development', 'Strategic Advisory', 'Commercial Modelling', 'Development Structuring', 'Audience Experience', 'Immersive Culture'],
    images: [
      { src: 'assets/experience/moir-2.jpg', tone: 'dark' },
      { src: 'assets/experience/moir-3.jpeg', tone: 'dark' },
      { src: 'assets/experience/moir-1.jpg', tone: 'dark' },
      { src: 'assets/experience/moir-4.jpg', tone: 'dark' },
      { src: 'assets/experience/moir-5.jpg', tone: 'dark' },
      { src: 'assets/experience/moir-6.jpeg', tone: 'dark' },
      { src: 'assets/experience/moir-7.jpeg', tone: 'dark' },
      { src: 'assets/experience/moir-8.jpeg', tone: 'dark' },
    ],
  },
  {
    id: 'london-nye',
    title: 'London New Year\u2019s Eve Fireworks',
    label: 'Civic Spectacle',
    projectType: 'Executive Production',
    year: '2015 — 2018',
    role: 'Creative Producer',
    client: 'Mayor of London',
    agency: 'Jack Morton Worldwide',
    tagline: 'One of the world\u2019s largest live broadcast spectacles — 12 million BBC viewers, 250,000 live.',
    body: [
      'Creative Producer across four consecutive editions of London\u2019s New Year\u2019s Eve fireworks — one of the world\u2019s largest live broadcast spectacles, viewed annually by more than 12 million BBC viewers and attended by over 250,000 people live.',
      'Led multi-agency coordination across pyrotechnics, live broadcast, public realm operations, audience management and stakeholder governance.',
      'Also supported the strategic transition of the event from unrestricted public access to a fully ticketed operational model — establishing frameworks still referenced across major public events in London today.',
    ],
    disciplines: ['Public Event', 'Live', 'Public Realm', 'Culture'],
    tags: ['Executive Production', 'Civic Operations', 'Audience Infrastructure', 'Broadcast Spectacle', 'Governance', 'Public Realm Strategy'],
    images: [
      { src: 'assets/experience/nye-hero.jpg', tone: 'dark' },
      { src: 'assets/experience/nye18-fw-8.jpg', tone: 'dark' },
      { src: 'assets/experience/nye18-rv-2.jpg', tone: 'dark' },
      { src: 'assets/experience/nye18-rv-3.jpg', tone: 'dark' },
      { src: 'assets/experience/nye18-rv-8.jpg', tone: 'dark' },
      { src: 'assets/experience/nye18-rv-6b.jpg', tone: 'dark' },
      { src: 'assets/experience/nye18-rv-8b.jpg', tone: 'dark' },
      { src: 'assets/experience/nye18-rv-31.jpg', tone: 'dark' },
      { src: 'assets/experience/nye18-prep-2.jpg', tone: 'dark' },
      { src: 'assets/experience/nye18-prep-7.jpg', tone: 'dark' },
      { src: 'assets/experience/nye18-prep-11.jpg', tone: 'dark' },
      { src: 'assets/experience/nye18-prep-12.jpg', tone: 'dark' },
      { src: 'assets/experience/nye18-prep-13.jpg', tone: 'dark' },
      { src: 'assets/experience/nye18-prep-15.jpg', tone: 'dark' },
      { src: 'assets/experience/nye18-prep-16.jpg', tone: 'dark' },
      { src: 'assets/experience/nye18-prep-17.jpg', tone: 'dark' },
      { src: 'assets/experience/nye18-photo1.jpg', tone: 'dark' },
      { src: 'assets/experience/nye15-001.jpg', tone: 'dark' },
      { src: 'assets/experience/nye15-003.jpg', tone: 'dark' },
      { src: 'assets/experience/nye15-005.jpg', tone: 'dark' },
      { src: 'assets/experience/nye15-009.jpg', tone: 'dark' },
      { src: 'assets/experience/nye15-021.jpg', tone: 'dark' },
    ],
  },
  {
    id: 'f1-live',
    title: 'Formula 1 — F1 Live London',
    label: 'Public Realm',
    projectType: 'Executive Production',
    year: '2017',
    role: 'Executive Producer',
    client: 'Formula One',
    agency: 'Velocity Experience',
    tagline: 'Whitehall and Trafalgar Square transformed into a fan festival of motorsport and entertainment.',
    body: [
      'Executive Producer for Formula One\u2019s large-scale takeover of central London, transforming Whitehall and Trafalgar Square into a city-wide live entertainment and motorsport experience.',
      'Led integrated production and operational delivery across live performance, motorsport spectacle, public audience management, hospitality and stakeholder coordination.',
      'The project attracted more than 100,000 attendees and formed part of Formula One\u2019s repositioning under Liberty Media as a broader entertainment platform.',
    ],
    disciplines: ['Public Event', 'Live', 'Public Realm', 'Sport'],
    tags: ['Executive Production', 'Audience Infrastructure', 'Civic Operations', 'Live Entertainment', 'Stakeholder Governance'],
    images: [
      { src: 'assets/experience/f1-hero.jpg' },
      { type: 'video', src: 'assets/experience/videos/f1-live-1.mp4', poster: 'assets/experience/f1-hero.jpg' },
      { src: 'assets/experience/f1-ext.jpeg' },
      { src: 'assets/experience/f1-crowd-stage.jpg' },
      { src: 'assets/experience/f1-live.jpg' },
      { src: 'assets/experience/f1-getty-1.jpg' },
      { src: 'assets/experience/f1-getty-2.jpg' },
      { src: 'assets/experience/f1-1.jpeg' },
      { src: 'assets/experience/f1-2.jpeg' },
      { src: 'assets/experience/f1-4.jpeg' },
      { src: 'assets/experience/f1-5.jpeg' },
      { src: 'assets/experience/f1-6.jpeg' },
      { src: 'assets/experience/f1-8.jpeg' },
      { src: 'assets/experience/f1-9.jpeg' },
      { src: 'assets/experience/f1-10.jpeg' },
      { src: 'assets/experience/f1-11.jpeg' },
      { src: 'assets/experience/f1-12.jpeg' },
      { src: 'assets/experience/f1-13.jpeg' },
      { src: 'assets/experience/f1-16.jpeg' },
      { src: 'assets/experience/f1-17.jpeg' },
      { src: 'assets/experience/f1-18.jpeg' },
      { src: 'assets/experience/f1-cc-9134.jpg' },
    ],
  },
  {
    id: 'rtps',
    title: 'Real-Time Systems for Live Events',
    label: 'Emerging Performance Technologies',
    projectType: 'Innovation Strategy & Real-Time Pipeline Development',
    year: '2023 — 2025',
    role: 'Executive Producer & Project Lead',
    client: 'Dimension Studio · DNEG 360',
    agency: null,
    tagline: 'Application of real-time and emerging technologies developed for film and virtual production into live entertainment and immersive experience environments.',
    outcome: 'Bridging the gap between cinematic production technologies and scalable audience-facing experiences — applied across global sport, live music, immersive culture and emerging IP-led platforms.',
    scope: [
      'Real-time rendering systems',
      'Virtual production workflows',
      'AI-assisted content pipelines',
      'Performance capture integration',
      'Unreal Engine ecosystems',
      'Live entertainment applications',
      'Touring scalability strategy',
      'Cross-platform production frameworks',
    ],
    body: [
      'Development and strategic application of real-time production technologies originally developed for film, virtual production and VFX — translated into scalable live entertainment, immersive experiences and next-generation performance systems.',
      'Working through Dimension Studio and DNEG 360, the work spanned digital twins of live venues, synchronised physical and virtual lighting, real-time scenic extension, metahuman performance workflows, AI-assisted content pipelines and audience-facing real-time interaction. The focus throughout: how cinematic production technologies can reshape the economics, scalability and creative flexibility of live entertainment.',
      'Applied across the OMEGA Pavilion at the Paris 2024 Olympics, Floating Points and Røyksopp at HERE (Outernet, London), Requiem in Motion with Epic Games and ENO, and Terminal 1 at Glastonbury Festival — sitting at the convergence of film, games, immersive culture and live performance.',
    ],
    disciplines: ['IP Development', 'Live', 'Immersive', 'Technology'],
    tags: ['Real-Time Production', 'Virtual Production', 'AI Pipelines', 'Performance Capture', 'Unreal Engine', 'Digital Humans', 'Innovation Strategy', 'Live Entertainment Innovation'],
    images: [
      { type: 'video', src: 'assets/experience/videos/royksopp-3.mp4', poster: 'assets/experience/royksopp.jpg', tone: 'dark' },
      { type: 'video', src: 'assets/experience/videos/floating-points-1.mp4', poster: 'assets/experience/floating-points-1.jpg', tone: 'dark' },
      { src: 'assets/experience/omega-2.jpg', tone: 'dark' },
      { src: 'assets/experience/omega-3.jpg', tone: 'dark' },
      { src: 'assets/experience/omega-4.jpg', tone: 'dark' },
      { src: 'assets/experience/omega-5.jpg', tone: 'dark' },
      { src: 'assets/experience/omega-6.jpg', tone: 'dark' },
      { src: 'assets/experience/omega-7.jpg', tone: 'dark' },
      { src: 'assets/experience/omega-8.jpg', tone: 'dark' },
      { src: 'assets/experience/omega-9.jpg', tone: 'dark' },
      { src: 'assets/experience/floating-points-2.jpg', tone: 'dark' },
      { src: 'assets/experience/fp-3.jpeg', tone: 'dark' },
      { src: 'assets/experience/fp-7.jpg', tone: 'dark' },
      { src: 'assets/experience/fp-sg-1.jpg', tone: 'dark' },
      { src: 'assets/experience/fp-sg-2.jpg', tone: 'dark' },
      { src: 'assets/experience/fp-outernet-2.jpg', tone: 'dark' },
      { src: 'assets/experience/fp-outernet-3.jpg', tone: 'dark' },
      { src: 'assets/experience/royksopp.jpg', tone: 'dark' },
      { src: 'assets/experience/royksopp-2.jpg', tone: 'dark' },
      { src: 'assets/experience/royksopp-3.jpg', tone: 'dark' },
      { src: 'assets/experience/royksopp-4.jpg', tone: 'dark' },
      { src: 'assets/experience/royksopp-5.jpg', tone: 'dark' },
      { src: 'assets/experience/terminal-1.jpeg', tone: 'dark' },
      { src: 'assets/experience/terminal-banksy.jpg', tone: 'dark' },
      { src: 'assets/experience/terminal-vr-1.jpg', tone: 'dark' },
      { src: 'assets/experience/terminal-vr-2.jpg', tone: 'dark' },
      { src: 'assets/experience/terminal-poster.jpeg', tone: 'dark' },
      { src: 'assets/experience/requiem-still.jpg', tone: 'dark' },
    ],
  },
  {
    id: 'great-ny',
    title: 'GREAT Campaign — New York',
    label: 'International Cultural Campaign',
    projectType: 'Executive Production & International Programme Coordination',
    year: '2022',
    role: 'Executive Producer',
    client: 'UK Government GREAT',
    agency: 'M&C Saatchi',
    tagline: 'A city-wide international cultural campaign across New York following the lifting of Covid restrictions — promoting British creativity, innovation, sport, food and music.',
    outcome: 'Coordinated multi-partner delivery across UK and US stakeholders, venues, agencies and public-facing campaign activity — landing British soft-power presence across one of the world\u2019s most contested cultural markets.',
    scope: [
      'Multi-partner programme coordination',
      'International stakeholder management',
      'Cultural campaign delivery',
      'Public activation strategy',
      'Experiential programming',
      'Cross-sector production management',
      'Live event integration',
      'UK / US operational coordination',
    ],
    body: [
      'Executive Producer for a large-scale programme of cultural activations across New York celebrating British creativity, innovation, music, food and sport.',
      'The programme combined immersive experiences, hospitality, public installation and cultural storytelling delivered across multiple venues and stakeholders within a high-profile international campaign environment.',
      'Activations included an authentic Premier League matchday experience, AI dining with Bompas & Parr, cooking with Nadiya Hussain, Sofar Sounds live music events and a city-wide PR campaign installing iconic British red telephone boxes across New York.',
      'Delivered during the reopening phase following Covid restrictions, requiring complex coordination across UK and US partners, venues, agencies and public-facing campaign activity.',
    ],
    disciplines: ['Live', 'Culture', 'Commercial Strategy'],
    tags: ['Executive Production', 'Cultural Campaign', 'International Activation', 'Experiential Programming', 'Stakeholder Coordination', 'Soft Power', 'Multi-Partner Delivery'],
    images: [
      { src: 'assets/experience/great-nadiya-hero.jpg' },
      { src: 'assets/experience/great-innovation.jpg' },
      { src: 'assets/experience/great-bfa-1.jpg' },
      { src: 'assets/experience/great-bfa-2.jpg' },
      { src: 'assets/experience/great-bfa-3.jpg' },
      { src: 'assets/experience/great-bfa-4.jpg' },
      { src: 'assets/experience/great-bfa-5.jpg' },
      { src: 'assets/experience/great-bfa-6.jpg' },
      { src: 'assets/experience/great-bfa-7.jpg' },
      { src: 'assets/experience/great-2.webp' },
      { src: 'assets/experience/great-1.webp' },
      { src: 'assets/experience/great-3.webp' },
      { src: 'assets/experience/great-4.jpg' },
      { src: 'assets/experience/great-5.jpg' },
      { src: 'assets/experience/great-6.webp' },
    ],
  },
];

const ARCHIVE = [
  {
    id: 'floating-points',
    title: 'Floating Points · HERE',
    label: 'Real-Time Hybrid Production',
    projectType: 'Real-Time Systems Development',
    client: 'Floating Points · Hamill Industries · HERE at Outernet · Dimension Studio',
    agency: null,
    role: 'Executive Producer / Real-Time Systems Lead',
    discipline: 'Real-Time Production',
    year: '2025',
    disciplines: ['Live', 'Technology'],
    tagline: 'Real-time synchronisation of physical and virtual lighting systems using a digital twin performance environment.',
    outcome: 'Part of broader exploration into how virtual production technologies developed for film can reshape live music, touring and immersive entertainment environments.',
    scope: [
      'Digital twin environments',
      'Real-time rendering systems',
      'Hybrid physical / virtual production',
      'Zero-latency visual synchronisation',
      'Unreal Engine workflows',
      'Live performance technology',
      'Real-time lighting control',
      'Emerging entertainment systems',
    ],
    body: [
      'A live exploration of a hybrid real-time lighting and visual control system developed using a digital twin of HERE at Outernet, London.',
      'Created in collaboration with electronic artist Floating Points and visuals producer Hamill Industries, the project explored how physical and virtual lighting environments could operate as a synchronised real-time performance system.',
      'Real and virtual lighting rigs were controlled simultaneously by lighting director Will Potts, while visual content was synchronised across physical and virtual screens with effectively zero perceptible latency.',
    ],
    tags: ['Real-Time Production', 'Digital Twin', 'Hybrid Production', 'Virtual Production', 'Real-Time Lighting', 'Live Entertainment Innovation', 'Emerging Entertainment Systems'],
    images: [
      { src: 'assets/experience/floating-points-1.jpg', tone: 'dark' },
      { type: 'video', src: 'assets/experience/videos/floating-points-1.mp4', poster: 'assets/experience/floating-points-1.jpg', tone: 'dark' },
      { src: 'assets/experience/fp-3.jpeg', tone: 'dark' },
      { src: 'assets/experience/fp-4.jpeg', tone: 'dark' },
      { src: 'assets/experience/fp-7.jpg', tone: 'dark' },
      { src: 'assets/experience/fp-sg-1.jpg', tone: 'dark' },
      { src: 'assets/experience/fp-sg-2.jpg', tone: 'dark' },
      { src: 'assets/experience/floating-points-2.jpg', tone: 'dark' },
      { src: 'assets/experience/fp-outernet-2.jpg', tone: 'dark' },
      { src: 'assets/experience/fp-outernet-3.jpg', tone: 'dark' },
    ],
  },
  {
    id: 'royksopp',
    title: 'Røyksopp · HERE',
    label: 'Real-Time Hybrid Production',
    projectType: 'Real-Time Systems Development',
    client: 'Røyksopp · HERE at Outernet · Dimension Studio',
    agency: null,
    role: 'Executive Producer / Hybrid Production Systems',
    discipline: 'Real-Time Production',
    year: '2025',
    disciplines: ['Live', 'Technology'],
    tagline: 'Hybrid real-time lighting and virtual scenic environment developed for live electronic performance.',
    outcome: 'Part of broader research into how virtual production technologies developed for film and VFX can transform live music, touring and immersive entertainment experiences.',
    scope: [
      'Real-time rendering systems',
      'AI-assisted performance optimisation',
      'Virtual scenic environments',
      'Hybrid live / virtual production',
      'Digital twin workflows',
      'Unreal Engine ecosystems',
      'Real-time lighting integration',
      'Emerging touring technologies',
    ],
    body: [
      'Second-stage live exploration of a hybrid real-time lighting and virtual production system developed for Røyksopp at HERE at Outernet.',
      'The project expanded earlier testing through upgraded compute infrastructure, proprietary lighting fixture integration and AI-powered DLSS frame generation to improve real-time rendering performance and responsiveness.',
      'Developed through Dimension Studio, the system explored how physical and virtual production layers could operate together as a unified live performance environment, combining real-time lighting control, scenic extension and synchronised digital scenography.',
      'Additional testing incorporated 3D geometry and virtual scenic elements controlled directly from the lighting desk by lighting director David Ross, enabling synchronised interaction between physical lighting systems and virtual environments in real time.',
    ],
    tags: ['Real-Time Systems', 'Virtual Production', 'Live Entertainment', 'Hybrid Performance', 'Innovation', 'Immersive Technology', 'Digital Scenography'],
    images: [
      { src: 'assets/experience/royksopp.jpg', tone: 'dark' },
      { type: 'video', src: 'assets/experience/videos/royksopp-1.mp4', poster: 'assets/experience/royksopp.jpg', tone: 'dark' },
      { type: 'video', src: 'assets/experience/videos/royksopp-2.mp4', poster: 'assets/experience/royksopp-2.jpg', tone: 'dark' },
      { src: 'assets/experience/royksopp-2.jpg', tone: 'dark' },
      { src: 'assets/experience/royksopp-3.jpg', tone: 'dark' },
      { src: 'assets/experience/royksopp-4.jpg', tone: 'dark' },
      { src: 'assets/experience/royksopp-5.jpg', tone: 'dark' },
    ],
  },
  {
    id: 'terminal-1',
    title: 'Terminal 1',
    label: 'Immersive Innovation & Accessibility',
    projectType: 'Experimental Real-Time Systems',
    client: 'Glastonbury Festival',
    agency: 'Dimension Studio',
    role: 'Executive Producer / Innovation Lead',
    discipline: 'Real-Time / Immersive',
    year: '2025',
    disciplines: ['Live', 'Immersive', 'Technology'],
    tagline: 'Immersive accessibility and AI-driven real-time interactive systems developed for Glastonbury Festival\u2019s Terminal 1.',
    outcome: 'The accessibility workflow developed for Terminal 1 has since become a reference point for how immersive environments can better support audiences with additional access requirements.',
    scope: [
      'Accessibility innovation',
      'VR walkthrough systems',
      'Real-time audience interaction',
      'AI-powered face integration',
      'Avatar pipeline development',
      'Immersive installation systems',
      'Virtual production workflows',
      'Experimental live environments',
    ],
    body: [
      'Working with Glastonbury Festival\u2019s accessibility and production teams, the project included development of a VR headset walkthrough enabling audiences with accessibility requirements to experience the installation. This represented one of the first deployments of this technology within a live festival environment and established a benchmark for future experiential accessibility design.',
      'Alongside this, a real-time interactive installation captured audience faces live and integrated them into CCTV-style video environments using AI-powered face-swap technology and Dimension Studio\u2019s real-time pipeline infrastructure. The project formed part of broader exploration of the use of real-time technologies within interactive audience participation environments.',
    ],
    tags: ['Accessibility Innovation', 'Real-Time Systems', 'AI Interaction', 'Immersive Technology', 'Avatar Systems', 'Experimental Media', 'Festival Innovation'],
    images: [
      { src: 'assets/experience/terminal-1.jpeg', tone: 'dark' },
      { type: 'video', src: 'assets/experience/videos/terminal-1-1.mp4', poster: 'assets/experience/terminal-1.jpeg', tone: 'dark' },
      { type: 'video', src: 'assets/experience/videos/terminal-1-2a.mp4', poster: 'assets/experience/terminal-1.jpeg', tone: 'dark' },
      { type: 'video', src: 'assets/experience/videos/terminal-1-2b.mp4', poster: 'assets/experience/terminal-1.jpeg', tone: 'dark' },
      { type: 'video', src: 'assets/experience/videos/terminal-1-3.mp4', poster: 'assets/experience/terminal-banksy.jpg', tone: 'dark' },
      { src: 'assets/experience/terminal-banksy.jpg', tone: 'dark' },
      { src: 'assets/experience/terminal-vr-d1.jpg', tone: 'dark' },
      { src: 'assets/experience/terminal-vr-1.jpg', tone: 'dark' },
      { src: 'assets/experience/terminal-vr-2.jpg', tone: 'dark' },
      { src: 'assets/experience/terminal-vr-d2-67.jpg', tone: 'dark' },
      { src: 'assets/experience/terminal-vr-d2-68.jpg', tone: 'dark' },
      { src: 'assets/experience/terminal-vr-d3.jpg', tone: 'dark' },
      { src: 'assets/experience/terminal-cctv-1.jpg', tone: 'dark' },
      { src: 'assets/experience/terminal-cctv-2.jpg', tone: 'dark' },
    ],
  },
  {
    id: 'omega-pavilion',
    title: 'OMEGA Pavilion',
    label: 'Real-Time Interaction',
    projectType: 'Interactive Real-Time Systems',
    client: 'OMEGA · Smyle · Dimension Studio · Paris 2024 Olympics',
    agency: null,
    role: 'Executive Producer / Interactive Technology Lead',
    discipline: 'Real-Time Interactive',
    year: '2024',
    disciplines: ['Live', 'Technology', 'Sport'],
    tagline: 'Real-time interactive metahuman racing activation developed for the OMEGA Pavilion at Paris 2024.',
    outcome: 'Explored how technologies developed across film and virtual production can enable new forms of responsive audience participation within physical environments.',
    scope: [
      'Real-time audience interaction',
      'Motion capture systems',
      'Metahuman integration',
      'Avatar pipeline development',
      'Live tracking workflows',
      'Interactive sports environments',
      'Virtual production systems',
      'Experiential technology innovation',
    ],
    body: [
      'Executive Producer for an interactive real-time activation developed for the OMEGA Pavilion during the Paris 2024 Olympics.',
      'Created in collaboration with Smyle, the installation enabled members of the public to select and race against Olympic athletes within a live interactive environment using real-time tracking, motion capture and metahuman playback systems.',
      'The activation combined live performance technology, avatar pipelines and real-time rendering workflows to create a responsive audience experience where participants competed directly against digital metahuman representations of elite athletes.',
      'The project formed part of broader exploration into how motion capture, gaming engines and virtual production technologies can reshape audience interaction within live entertainment, sport and brand environments.',
    ],
    tags: ['Real-Time Systems', 'Metahuman Technology', 'Interactive Experience', 'Motion Capture', 'Avatar Systems', 'Olympic Activation', 'Experiential Innovation'],
    images: [
      { src: 'assets/experience/omega-1.jpg', tone: 'dark' },
      { type: 'video', src: 'assets/experience/videos/omega-1.mp4', poster: 'assets/experience/omega-1.jpg', tone: 'dark' },
      { type: 'video', src: 'assets/experience/videos/omega-2.mp4', poster: 'assets/experience/omega-2.jpg', tone: 'dark' },
      { type: 'video', src: 'assets/experience/videos/omega-3.mp4', poster: 'assets/experience/omega-3.jpg', tone: 'dark' },
      { src: 'assets/experience/omega-2.jpg', tone: 'dark' },
      { src: 'assets/experience/omega-3.jpg', tone: 'dark' },
      { src: 'assets/experience/omega-4.jpg', tone: 'dark' },
      { src: 'assets/experience/omega-5.jpg', tone: 'dark' },
      { src: 'assets/experience/omega-6.jpg', tone: 'dark' },
      { src: 'assets/experience/omega-7.jpg', tone: 'dark' },
      { src: 'assets/experience/omega-8.jpg', tone: 'dark' },
      { src: 'assets/experience/omega-9.jpg', tone: 'dark' },
    ],
  },
  {
    id: 'requiem',
    title: 'Requiem in Motion',
    label: 'Real-Time Cultural Performance',
    projectType: 'Real-Time Performance Systems',
    client: 'JV led by Gideon Berger Studio',
    agency: 'Epic Games · ENO · Akram Khan Studio · Dimension Studio',
    role: 'Executive Producer / Real-Time Performance Systems',
    discipline: 'Real-Time Production',
    year: '2024',
    disciplines: ['Immersive', 'Technology', 'Culture'],
    tagline: 'Real-time motion-captured immersive performance environment combining live choreography, virtual production and digital scenography.',
    outcome: 'The collaboration brought together leading practitioners across performance, technology and immersive media to explore future-facing approaches to cultural production.',
    scope: [
      'Real-time motion capture',
      'Unreal Engine workflows',
      'Immersive visual storytelling',
      'Virtual production systems',
      'Digital scenography',
      'Live performance integration',
      'Cultural technology innovation',
      'Hybrid physical / digital environments',
    ],
    body: [
      'Executive Producer for Requiem in Motion, an experimental large-scale cultural production combining real-time motion capture, immersive visual environments and live choreography.',
      'Developed in collaboration with Gideon Berger Studio, Epic Games, ENO, Akram Khan Studio and Dimension Studio, the project explored how technologies originating from gaming, film and virtual production could be integrated into live cultural performance.',
      'The production combined motion-captured performers, Unreal Engine-driven environments and synchronised visual systems to create a responsive immersive stage environment blending physical and digital scenography in real time.',
      'An exploration into how virtual production workflows and real-time rendering systems can reshape live cultural performance, opera, dance and immersive storytelling.',
    ],
    tags: ['Real-Time Systems', 'Motion Capture', 'Virtual Production', 'Immersive Performance', 'Cultural Innovation', 'Unreal Engine', 'Digital Scenography'],
    link: { href: 'https://requieminmotion.com/', label: 'Visit the project website', note: 'A full video of the production can be found on the project website.' },
    images: [
      { src: 'assets/experience/requiem-still.jpg', tone: 'dark' },
      { type: 'video', src: 'assets/experience/videos/requiem-01.mp4', poster: 'assets/experience/requiem-still.jpg', tone: 'dark' },
      { type: 'video', src: 'assets/experience/videos/requiem-03.mp4', poster: 'assets/experience/requiem-2.webp', tone: 'dark' },
      { src: 'assets/experience/requiem-trim-1.gif', tone: 'dark' },
      { src: 'assets/experience/requiem-2.webp', tone: 'dark' },
    ],
  },
  {
    id: 'mlb',
    title: 'MLB London Series',
    label: 'International Sports Market Entry',
    projectType: 'Audience Strategy & Commercial Development',
    client: 'Major League Baseball',
    agency: 'CSM Sport & Entertainment',
    role: 'Strategic Advisory / Audience & Fan Engagement',
    discipline: 'Market Entry',
    year: '2018 — 2019',
    disciplines: ['Live', 'Sport', 'Commercial Strategy'],
    tagline: 'Strategic audience development and fan engagement frameworks supporting MLB\u2019s expansion into the UK market.',
    outcome: 'The work focused on how global sports IP can build cultural relevance and sustainable audience growth through experiential engagement and live entertainment strategy.',
    scope: [
      'International market-entry strategy',
      'Audience development',
      'Fan engagement ecosystems',
      'Commercial modelling',
      'Sports entertainment positioning',
      'Live event strategy',
      'Cultural localisation',
      'Rights-holder advisory',
    ],
    body: [
      'Strategic advisory support for Major League Baseball\u2019s expansion into the UK market through the MLB London Series.',
      'Working within CSM\u2019s Global Consulting division, the project focused on audience development, fan engagement strategy and commercial positioning frameworks designed to support MLB\u2019s long-term European growth ambitions.',
      'The work explored how live experiences, cultural positioning and scalable fan engagement ecosystems could help localise MLB for UK audiences while building sustainable commercial relevance beyond individual event cycles.',
      'An early exploration into how sports, live entertainment and experiential engagement increasingly converge within modern audience development strategies.',
    ],
    tags: ['Audience Strategy', 'Fan Engagement', 'Sports Entertainment', 'Commercial Modelling', 'International Expansion', 'Rights Holder Advisory', 'Live Experience Strategy'],
    images: [
      { src: 'assets/experience/mlb-2.jpg' },
      { src: 'assets/experience/mlb-1.jpg' },
      { src: 'assets/experience/mlb-3.avif' },
      { src: 'assets/experience/mlb-4.webp' },
    ],
  },
  {
    id: 'vodafone-firsts',
    title: 'Vodafone Firsts',
    label: 'Experiential Innovation Programme',
    projectType: 'Multi-Year Innovation Programme',
    client: 'Vodafone',
    agency: 'Wasserman',
    role: 'Executive Producer / Experiential Innovation',
    discipline: 'Brand Experience',
    year: '2014',
    disciplines: ['Live', 'Culture', 'Technology'],
    tagline: 'A pioneering experiential platform creating first-of-their-kind public experiences across music, technology, culture and live entertainment.',
    outcome: 'Vodafone Firsts became an early benchmark for audience-first experiential marketing combining technology, culture and large-scale public participation.',
    scope: [
      'Experiential innovation',
      'Audience participation',
      'Cultural programming',
      'Live experiences',
      'Emerging technologies',
      'Multi-partner production',
    ],
    body: [
      'Executive production across Vodafone Firsts \u2014 a multi-year programme of experimental public experiences developed with Wasserman exploring new intersections between live entertainment, technology, participation and cultural storytelling.',
      'The programme focused on creating highly shareable audience-first activations combining emerging technologies, immersive design and large-scale public engagement across music, sport and cultural environments.',
    ],
    tags: ['Experiential Innovation', 'Audience Participation', 'Cultural Programming', 'Live Experiences', 'Emerging Technologies'],
    images: [
      { src: 'assets/experience/vodafone-nye.jpg', tone: 'dark' },
      { src: 'assets/experience/vodafone-firsts.jpg' },
      { src: 'assets/experience/vodafone-skate.jpg' },
      { src: 'assets/experience/vodafone-nye-2.jpg', tone: 'dark' },
      { src: 'assets/experience/vodafone-firsts-2.jpg' },
      { src: 'assets/experience/vodafone-skate-2.jpg' },
    ],
  },
  {
    id: 'vodafone-fireworks',
    title: 'World\u2019s First Multi-Sensory Fireworks Display',
    label: 'Vodafone Firsts \u00b7 Multi-Sensory',
    projectType: 'Experimental Sensory Experience',
    client: 'Vodafone',
    agency: 'Wasserman \u00b7 Bompas & Parr',
    role: 'Executive Producer',
    discipline: 'Multi-Sensory Experience',
    year: '2014',
    disciplines: ['Live', 'Culture', 'Technology'],
    tagline: 'World-first multi-sensory takeover of London’s New Year’s Eve fireworks integrating scent, flavour and immersive environmental effects at broadcast scale.',
    outcome: 'One of the earliest large-scale explorations into how sensory engineering and immersive environmental effects could transform audience experience within globally broadcast public events — demonstrating how large-scale public events could evolve beyond visual spectacle into fully immersive multi-sensory audience environments.',
    scope: [
      'Multi-sensory experience design',
      'Broadcast-scale live events',
      'Environmental storytelling',
      'Sensory engineering systems',
      'Immersive public spectacle',
      'Audience participation design',
      'Experimental live environments',
      'Large-scale public engagement',
    ],
    body: [
      'Executive production support for a world-first multi-sensory takeover of London’s New Year’s Eve fireworks, developed with food artists Bompas & Parr.',
      'Delivered across London’s internationally broadcast New Year celebrations, the project transformed the traditional fireworks experience into a large-scale immersive sensory environment combining pyrotechnics, scent diffusion, edible effects and environmental storytelling.',
      'The work reached an estimated live audience of over 500,000 people across central London, with more than 50,000 spectators positioned along Victoria Embankment experiencing synchronised flavour and scent effects integrated directly into the fireworks choreography and soundtrack. The event was broadcast live to an audience of more than 12 million viewers via the BBC.',
      'To achieve the effect, existing stadium SFX systems were re-engineered into food-safe dispersal systems capable of delivering ethically produced and allergen-free fruit flavour mists at large scale. The experience included peach mist, orange-flavoured bubbles and the world’s first edible banana confetti, synchronised to the live fireworks display and accompanying soundtrack.',
      'Audience participation extended beyond the live environment through distributed sweets and scratch-and-sniff programmes designed to deepen sensory immersion across the event experience.',
    ],
    link: {
      href: 'https://bompasandparr.com/case-study/flavour-fireworks/',
      label: 'Bompas & Parr · Flavour Fireworks case study',
      note: 'Supporting reference — Bompas & Parr documentation of the Flavour Fireworks programme.',
    },
    tags: ['Multi-Sensory Experience', 'Broadcast Events', 'Public Spectacle', 'Sensory Storytelling', 'Immersive Environments', 'Environmental Design', 'Experimental Live Events', 'Audience Immersion'],
    images: [
      { src: 'assets/experience/vodafone-nye-10.jpg' },
      { type: 'video', src: 'assets/experience/videos/vodafone-nye-2.mp4', poster: 'assets/experience/vodafone-nye-10.jpg', tone: 'dark' },
      { src: 'assets/experience/vodafone-nye.jpg', tone: 'dark' },
      { src: 'assets/experience/vodafone-nye-2.jpg', tone: 'dark' },
      { src: 'assets/experience/vodafone-nye-3.jpg', tone: 'dark' },
      { src: 'assets/experience/vodafone-nye-4.jpg', tone: 'dark' },
      { src: 'assets/experience/vodafone-nye-5.jpg' },
      { src: 'assets/experience/vodafone-nye-6.jpg' },
      { src: 'assets/experience/vodafone-nye-7.jpg' },
      { src: 'assets/experience/vodafone-nye-8.jpg' },
      { src: 'assets/experience/vodafone-nye-9.jpg' },
      { src: 'assets/experience/vodafone-nye-11.jpg', tone: 'dark' },
      { src: 'assets/experience/vodafone-nye-12.jpg' },
      { src: 'assets/experience/vodafone-nye-13.jpg' },
      { src: 'assets/experience/vodafone-nye-14.jpg' },
      { src: 'assets/experience/vodafone-nye-15.jpeg' },
      { src: 'assets/experience/vodafone-nye-16.jpeg' },
      { src: 'assets/experience/vodafone-nye-17.jpeg' },
      { src: 'assets/experience/vodafone-nye-18.jpg' },
      { src: 'assets/experience/vodafone-nye-19.jpg' },
      { src: 'assets/experience/vodafone-nye-20.jpg', tone: 'dark' },
      { src: 'assets/experience/vodafone-nye-21.jpg' },
    ],
  },
  {
    id: 'vodafone-skate',
    title: 'Skate with Stefan Janoski',
    label: 'Community-Led Skate Culture Programme',
    projectType: 'Public Space Regeneration · Youth Culture',
    client: 'Vodafone',
    agency: 'Wasserman',
    role: 'Executive Producer',
    discipline: 'Youth Culture',
    year: '2014',
    disciplines: ['Live', 'Sport', 'Culture'],
    tagline: 'Community-led skateboarding project restoring a neglected Budapest skatepark and reconnecting young people through reclaimed public space.',
    outcome: 'A socially meaningful community activation combining youth culture, public space regeneration and participatory live experience — exploring how brand-supported live work could create lasting community impact beyond short-term audience engagement.',
    scope: [
      'Community-led activation',
      'Youth culture engagement',
      'Public space regeneration',
      'Participatory live experiences',
      'Skate culture programming',
      'Community audience participation',
      'Experiential storytelling',
      'Legacy-focused public engagement',
    ],
    body: [
      'Executive production for a Vodafone Firsts project developed around professional skateboarder Stefan Janoski and the restoration of a neglected skatepark in Budapest.',
      'Located within an overgrown public park surrounded by residential tower blocks, the site had become disused despite being home to a large local youth community with few remaining recreational spaces. Working with Stefan Janoski and local partners, the project explored how skate culture and participatory live experiences could help reactivate the space and reconnect young people through shared community activity.',
      'The existing skatepark was stripped back and rebuilt into a new wooden skate environment, with construction closely followed by local residents over several weeks as anticipation for the reopening grew across the neighbourhood.',
      'Once completed, the park launched through a celebratory public event featuring Stefan Janoski, local skaters, media and civic representatives including the city mayor. The project created both an immediate cultural moment and a lasting community legacy, with the park continuing to operate as an active skate space where Stefan and his local crew still support skateboarding sessions and youth participation.',
      'At its core, the project used skateboarding as a mechanism for rebuilding social connection and reclaiming underused urban space through collective participation.',
    ],
    tags: ['Youth Culture', 'Community Engagement', 'Public Space Regeneration', 'Participatory Experiences', 'Skate Culture', 'Experiential Storytelling', 'Live Community Events', 'Legacy Programming'],
    images: [
      { src: 'assets/experience/vodafone-skate.jpg' },
      { type: 'video', src: 'assets/experience/videos/vodafone-skate-1.mp4', poster: 'assets/experience/vodafone-skate.jpg' },
      { src: 'assets/experience/vodafone-skate-2.jpg' },
      { src: 'assets/experience/vodafone-skate-3.jpg' },
      { src: 'assets/experience/vodafone-skate-4.jpg' },
      { src: 'assets/experience/vodafone-skate-5.jpg' },
      { src: 'assets/experience/vodafone-skate-6.jpg' },
      { src: 'assets/experience/vodafone-skate-7.jpg' },
      { src: 'assets/experience/vodafone-skate-8.jpg' },
      { src: 'assets/experience/vodafone-skate-9.jpg' },
    ],
  },
  {
    id: 'vodafone-booka',
    title: 'Interactive Concert \u2014 Booka Shade',
    label: 'Vodafone Firsts \u00b7 Immersive Music',
    projectType: 'Interactive Performance',
    client: 'Vodafone',
    agency: 'Wasserman \u00b7 Booka Shade',
    role: 'Executive Producer',
    discipline: 'Immersive Music',
    year: '2014',
    disciplines: ['Live', 'Culture', 'Technology'],
    tagline: 'Interactive electronic music performance exploring audience connection through responsive live systems.',
    outcome: 'An early experimental immersive music performance exploring how technology could deepen audience connection within live electronic concert environments.',
    scope: [
      'Interactive live performance',
      'Electronic music environments',
      'Audience-responsive visuals',
      'Immersive concert design',
      'Live visual integration',
      'Participatory audience experiences',
    ],
    body: [
      'Production of an interactive electronic music performance with Booka Shade exploring how live visuals, responsive systems and audience interaction could create a more immersive concert experience.',
      'Designed as an experimental live environment, the project combined electronic music performance with audience-responsive visual systems intended to deepen emotional connection, atmosphere and audience participation within the live show.',
      'Part of a broader exploration into how technology and live performance could create more participatory and immersive audience experiences within electronic music environments.',
    ],
    tags: ['Immersive Music', 'Interactive Performance', 'Audience Participation', 'Electronic Music', 'Live Visuals', 'Experiential Performance'],
    images: [
      { src: 'assets/experience/vodafone-firsts.jpg' },
      { type: 'video', src: 'assets/experience/videos/vodafone-booka-1.mp4', poster: 'assets/experience/vodafone-firsts.jpg' },
      { src: 'assets/experience/vodafone-firsts-2.jpg' },
      { src: 'assets/experience/vodafone-firsts-3.jpeg' },
      { src: 'assets/experience/vodafone-firsts-4.jpg' },
    ],
  },
  {
    id: 'edf',
    title: 'EDF Energy of the Nation',
    label: 'London 2012 · Real-Time Public Data Visualisation',
    projectType: 'Real-Time Data Visualisation · Olympic Civic Activation',
    client: 'EDF',
    agency: 'Wasserman',
    role: 'Executive Producer / National Experience Programme',
    discipline: 'Sports Brand Experience',
    year: '2012',
    disciplines: ['Live', 'Public Realm', 'Culture', 'Technology'],
    tagline: 'World-first Twitter-powered light installation visualising the mood of the nation throughout the London 2012 Olympics.',
    outcome: 'An early exploration into how live social data could power responsive public environments and transform audience participation into real-time collective visual storytelling — capturing the collective emotional rhythm of the Olympics and turning it into a shared civic experience.',
    scope: [
      'Real-time data visualisation',
      'Civic-scale public engagement',
      'Live audience participation',
      'Responsive lighting environments',
      'Olympic cultural programming',
      'Public storytelling systems',
      'Interactive installations',
      'Large-scale experiential innovation',
    ],
    body: [
      'Executive production for EDF Energy’s “Energy of the Nation” — a landmark London 2012 Olympic activation developed with data artists SOSO Limited.',
      'The project transformed live public sentiment into a real-time city-scale lighting installation, scraping and analysing UK-wide Twitter data relating to the Olympics to measure national mood and emotional response throughout the Games.',
      'This live sentiment data drove dynamic real-time lighting sequences across the London Eye, creating the world’s first Twitter-powered light show and turning one of London’s most recognisable landmarks into a constantly evolving visualisation of national participation and Olympic engagement.',
      'Alongside the public installation, audiences could explore the campaign through a specially constructed “Mission Control” visitor experience floating on the Thames, where real-time data feeds, visualisations and Olympic sentiment analysis were brought together into an immersive public environment.',
      'The project formed one of the earliest large-scale explorations into how live data, audience participation and public infrastructure could combine to create responsive civic-scale storytelling environments.',
    ],
    link: {
      href: 'https://www.sosolimited.com/work/energy-of-the-nation/',
      label: 'SOSO Limited · Energy of the Nation case study',
      note: 'Supporting reference — SOSO Limited documentation of the Energy of the Nation real-time visualisation system.',
    },
    tags: ['Real-Time Data', 'Public Participation', 'Responsive Environments', 'Olympic Programming', 'Civic-Scale Installations', 'Live Visualisation', 'Interactive Public Art', 'Experiential Innovation'],
    images: [
      { src: 'assets/experience/edf-hero.jpg' },
      { type: 'video', src: 'assets/experience/videos/edf-1.mp4', poster: 'assets/experience/edf-hero.jpg' },
      { src: 'assets/experience/edf-montage-1.jpg' },
      { src: 'assets/experience/edf-1.jpeg' },
      { src: 'assets/experience/edf-3.jpeg' },
      { src: 'assets/experience/edf-4.jpeg' },
      { src: 'assets/experience/edf-5.jpeg' },
      { src: 'assets/experience/edf-6.jpeg' },
      { src: 'assets/experience/edf-7.jpeg' },
      { src: 'assets/experience/edf-8.jpeg' },
      { src: 'assets/experience/edf-10.jpeg' },
      { src: 'assets/experience/edf-283.jpg' },
      { src: 'assets/experience/edf-montage-2.jpg' },
      { src: 'assets/experience/edf-picture-1.jpg' },
    ],
  },
  {
    id: 'verizon-superbowl',
    title: 'Verizon Super Bowl',
    label: 'City-Scale Interactive Sports Spectacle',
    projectType: 'Interactive Sports Campaign · Landmark Lighting',
    client: 'Verizon',
    agency: 'Wasserman',
    role: 'Executive Producer / Sports Entertainment Activation',
    discipline: 'Sports Entertainment',
    year: '2014',
    disciplines: ['Live', 'Sport', 'Culture'],
    tagline: 'City-scale Super Bowl activation combining live audience participation, social interaction and real-time landmark lighting across New York.',
    outcome: 'One of the early large-scale explorations into how live social participation and responsive lighting environments could create city-scale audience storytelling experiences — transforming public participation into a live visual spectacle integrated directly into one of the world’s most recognisable urban landmarks.',
    scope: [
      'Sports entertainment activation',
      'Real-time audience participation',
      'Interactive public campaigns',
      'Architectural lighting environments',
      'Landmark event programming',
      'Live social data integration',
      'City-scale public engagement',
      'Experiential sports storytelling',
    ],
    body: [
      'Executive production for Verizon’s Super Bowl programme delivered across New York during Super Bowl week.',
      'The campaign centred around Verizon Powerhouse in Bryant Park — a large-scale public visitor experience combining live entertainment, audience participation and interactive sports engagement throughout the build-up to the game.',
      'At the centre of the programme was “Who’s Gonna Win” — an interactive public campaign inviting audiences to vote for their Super Bowl prediction via Twitter each day leading up to the final. Live social participation data was transformed into nightly real-time lighting shows projected across the Empire State Building, celebrating the winning team selection through dynamic architectural lighting sequences visible across the New York skyline.',
      'The campaign culminated during the Super Bowl Final itself, when the Empire State Building was transformed into a large-scale star-spangled banner lighting performance integrated into the wider halftime celebrations.',
      'The project combined public participation, real-time data interaction, landmark architecture and live entertainment into a highly visible city-scale sports engagement campaign.',
    ],
    tags: ['Sports Entertainment', 'Real-Time Participation', 'Architectural Lighting', 'Public Engagement', 'Interactive Campaigns', 'Landmark Activations', 'Live Data Integration', 'Experiential Storytelling'],
    images: [
      { src: 'assets/experience/verizon-empire.jpg' },
      { type: 'video', src: 'assets/experience/videos/verizon-1.mp4', poster: 'assets/experience/verizon-empire.jpg' },
      { type: 'video', src: 'assets/experience/videos/verizon-2.mp4', poster: 'assets/experience/verizon-empire.jpg' },
      { src: 'assets/experience/verizon-7.jpg' },
      { src: 'assets/experience/verizon-wedpm.jpg' },
      { src: 'assets/experience/verizon-campaign.jpg' },
    ],
  },
  {
    id: 'u2',
    title: 'U2 Experience & Innocence Tour',
    label: 'International Touring Production',
    projectType: 'Creative Production Support',
    client: 'U2',
    agency: 'Treatment Studio',
    role: 'Creative Producer',
    discipline: 'Touring Production',
    year: '2018',
    disciplines: ['Live', 'Culture'],
    tagline: 'Creative production support within U2\u2019s Experience & Innocence touring programme and associated live broadcast performances.',
    outcome: 'Working alongside internationally recognised creative and touring teams provided valuable insight into large-scale live entertainment systems and audience-focused performance design.',
    scope: [
      'Touring production support',
      'Live broadcast integration',
      'Creative production coordination',
      'Large-scale live entertainment',
      'Performance environments',
      'Audience experience systems',
      'Touring operations',
      'Live music production',
    ],
    body: [
      'Creative production support through Treatment Studio across selected elements of U2’s Experience & Innocence touring programme and associated live broadcast performances.',
      'Working alongside internationally recognised creative and touring teams, the role included support across touring production activity, broadcast moments and live performance environments operating at arena scale.',
      'The project provided experience within complex global touring systems combining large-format visuals, live broadcast integration and tightly choreographed audience environments shaped by U2 Creative Director Willie Williams.',
    ],
    tags: ['Touring Production', 'Live Music', 'Broadcast Performance', 'Creative Production', 'Audience Experience', 'Live Entertainment', 'Performance Systems'],
    images: [
      { src: 'assets/experience/u2-picture-1.jpg', tone: 'dark' },
      { src: 'assets/experience/u2-mathew.jpg', tone: 'dark' },
      { src: 'assets/experience/u2-ema-1.jpg', tone: 'dark' },
      { src: 'assets/experience/u2-ema-2.jpg', tone: 'dark' },
      { src: 'assets/experience/u2-ema-3.jpg', tone: 'dark' },
      { src: 'assets/experience/u2-ema-4.jpg', tone: 'dark' },
      { src: 'assets/experience/u2-ema-5.jpg', tone: 'dark' },
      { src: 'assets/experience/u2-9515.jpg', tone: 'dark' },
      { src: 'assets/experience/u2-9516.jpg', tone: 'dark' },
      { src: 'assets/experience/u2-9525.jpg', tone: 'dark' },
      { src: 'assets/experience/u2-screen.jpg', tone: 'dark' },
      { src: 'assets/experience/u2-j.jpg', tone: 'dark' },
      { src: 'assets/experience/u2-m.jpg', tone: 'dark' },
      { src: 'assets/experience/u2-n.jpg', tone: 'dark' },
      { src: 'assets/experience/u2-p.jpg', tone: 'dark' },
      { src: 'assets/experience/u2-q.jpg', tone: 'dark' },
      { src: 'assets/experience/u2-r.jpg', tone: 'dark' },
    ],
  },
  {
    id: 'rwc',
    title: 'Rugby World Cup Fan Zone',
    label: 'Trafalgar Square · Tournament Public Engagement',
    projectType: 'Tournament-Scale Public Engagement Environment',
    client: 'World Rugby',
    agency: 'Wasserman',
    role: 'Executive Producer',
    discipline: 'Audience Infrastructure',
    year: '2015',
    disciplines: ['Public Event', 'Live', 'Sport', 'Public Realm'],
    tagline: 'Tournament-long public fan zone transforming Trafalgar Square into a large-scale sports and cultural engagement environment.',
    outcome: 'A benchmark-setting public sports audience environment — demonstrating how major sporting tournaments could transform iconic civic spaces into large-scale participatory viewing experiences, and helping establish a blueprint for future large-scale public sports screening and fan engagement environments within central London.',
    scope: [
      'Tournament-scale public engagement',
      'Live sports screening environments',
      'Civic audience infrastructure',
      'Fan participation programming',
      'Sports entertainment operations',
      'Public realm activation',
      'Sponsor activation integration',
      'Multi-stakeholder coordination',
      'Rights-holder integration',
      'Civic stakeholder management',
      'Public authority liaison',
      'Large-scale live events',
    ],
    body: [
      'Executive production for the Rugby World Cup Fan Zone in Trafalgar Square — a tournament-long public engagement environment delivered throughout the Rugby World Cup.',
      'Operating for the duration of the tournament, the fan zone transformed Trafalgar Square into a large-scale live sports and public participation environment combining live match screenings, sponsor activations, food and beverage experiences, schools programming and interactive rugby experiences.',
      'At the centre of the site was a large-format public viewing screen, including the live screening of the Rugby World Cup Final — the first time live sport had ever been screened within Trafalgar Square.',
      'The programme also featured an inflatable rugby pitch, youth and schools engagement activity, public participation experiences and opportunities for audiences to interact with legendary rugby players alongside a range of sponsor-led activations and cultural programming.',
      'The delivery environment represented a strong example of complex multi-stakeholder event governance, balancing the operational requirements of public authorities, tournament rights holders, commercial sponsors and live audiences within one of London’s most high-profile civic spaces — maintaining safe, accessible and high-volume public audience operations throughout the tournament.',
      'The fan zone became one of the defining public audience environments of the tournament, attracting significant public attendance and extensive media coverage while setting a benchmark for future sports activation and live screening environments in central London.',
    ],
    tags: ['Sports Entertainment', 'Public Viewing Environments', 'Tournament Operations', 'Civic Events', 'Fan Engagement', 'Large-Scale Public Events', 'Public Realm Activation', 'Audience Infrastructure'],
    images: [
      { src: 'assets/experience/rwc-saturday.jpg' },
      { src: 'assets/experience/rwc-12189.jpg' },
      { src: 'assets/experience/rwc-12195.jpg' },
      { src: 'assets/experience/rwc-img-0017.jpg' },
      { src: 'assets/experience/rwc-leo.jpg' },
      { src: 'assets/experience/rwc-lwp-0061.jpg' },
      { src: 'assets/experience/rwc-lwp-0307.jpg' },
    ],
  },
  {
    id: 'olympic-parade',
    title: 'Olympic Heroes Parade',
    label: 'Manchester · BBC Live Broadcast Civic Celebration',
    projectType: 'Live Broadcast Civic Event',
    client: 'British Olympic Association',
    agency: null,
    role: 'Executive Producer',
    discipline: 'Public Event',
    year: '2016',
    disciplines: ['Public Event', 'Live', 'Public Realm', 'Sport'],
    tagline: 'Live broadcast civic celebration welcoming Team GB and Paralympic GB athletes home from the Rio 2016 Olympic and Paralympic Games.',
    outcome: 'A nationally visible civic celebration combining large-scale public audience operations and live BBC broadcast — marking the homecoming of Team GB and Paralympic GB through a culturally significant, broadcast-scale public event.',
    scope: [
      'Live broadcast events',
      'Civic celebration programmes',
      'Public realm activation',
      'Audience infrastructure',
      'Broadcast coordination',
      'Talent and athlete management',
      'City stakeholder coordination',
      'Large-scale public events',
    ],
    body: [
      'Executive production for the Olympic Heroes Parade and celebration event staged outside Manchester Town Hall following the Rio 2016 Olympic and Paralympic Games.',
      'Broadcast live on the BBC, the event brought together returning Team GB and Paralympic GB athletes for a large-scale public celebration combining live interviews, audience engagement and musical performances within Manchester city centre.',
      'The programme featured appearances from Olympic and Paralympic athletes alongside live performances from Rebecca Ferguson and the Kaiser Chiefs, creating a nationally visible civic celebration environment with significant public attendance and broadcast reach.',
      'The delivery environment required coordination across public authorities, city stakeholders, live broadcast operations, artist teams, athlete management and large-scale audience infrastructure within a highly visible public realm setting.',
    ],
    tags: ['Live Broadcast', 'Civic Events', 'Public Realm', 'Sports Entertainment', 'Audience Infrastructure', 'Broadcast Production', 'Cultural Programming', 'Public Celebration'],
    images: [
      { src: 'assets/experience/olympic-parade-hero.jpeg' },
      { src: 'assets/experience/olympic-team-gb.jpg' },
      { src: 'assets/experience/olympic-bbc.jpg' },
      { src: 'assets/experience/olympic-1.jpg' },
      { src: 'assets/experience/olympic-dm-1.jpg' },
      { src: 'assets/experience/olympic-dm-4.jpg' },
      { src: 'assets/experience/olympic-dm-27.jpg' },
      { src: 'assets/experience/olympic-dm-35.jpg' },
      { src: 'assets/experience/olympic-dm-38.jpg' },
      { src: 'assets/experience/olympic-dm-52.jpg' },
    ],
  },
  {
    id: 'onroundhay',
    title: 'OnRoundhay Festival',
    label: 'Community Outdoor Festival',
    projectType: 'Outdoor Festival Production',
    client: 'Leeds City Council',
    agency: null,
    role: 'Executive Producer',
    discipline: 'Cultural Programming',
    year: '2016',
    disciplines: ['Live', 'Public Realm', 'Culture'],
    tagline: 'A single-day family festival celebrating music, food and community culture in Roundhay Park.',
    outcome: 'Designed as an accessible public event bringing together music, food and family-focused cultural programming within a civic outdoor environment.',
    scope: [
      'Outdoor festival operations',
      'Community event delivery',
      'Public audience management',
      'Family programming',
      'Live entertainment coordination',
      'Site operations',
      'Public engagement',
    ],
    body: [
      'Executive production for OnRoundhay, a single-day outdoor family festival delivered in Leeds\u2019 Roundhay Park.',
      'The festival combined live music, food, family activities and community-focused programming within a large-scale public park environment, requiring integrated event operations, audience management and site coordination.',
      'The project focused on creating an accessible and welcoming public event balancing live entertainment with broad community participation.',
    ],
    tags: ['Festival Production', 'Community Events', 'Outdoor Events', 'Public Engagement', 'Family Programming', 'Live Entertainment'],
    images: [
      { src: 'assets/experience/onroundhay.jpg' },
      { src: 'assets/experience/onroundhay-2.jpg' },
      { src: 'assets/experience/onroundhay-3.jpg' },
      { src: 'assets/experience/onroundhay-4.jpg' },
      { src: 'assets/experience/onroundhay-5.jpg' },
      { src: 'assets/experience/onroundhay-6.jpg' },
      { src: 'assets/experience/onroundhay-7.jpg' },
    ],
  },
  {
    id: 'candy-crush',
    title: 'Candy Crush Launches',
    label: 'Experiential Brand Activations',
    projectType: 'Experiential Launch Production',
    client: 'King',
    agency: 'Jack Morton Worldwide',
    role: 'Executive Producer',
    discipline: 'Brand Experience',
    year: '2017 — 2018',
    disciplines: ['Live', 'Culture'],
    tagline: 'Large-scale experiential activations and partner events supporting Candy Crush launches and brand campaigns.',
    outcome: 'The programme explored how gaming brands could extend beyond digital platforms into immersive physical experiences and culturally visible public activations.',
    scope: [
      'Experiential launch production',
      'Branded entertainment environments',
      'Public audience engagement',
      'Immersive pop-up experiences',
      'Partner activations',
      'Live event production',
      'Consumer participation',
      'Cultural marketing campaigns',
    ],
    body: [
      'Executive production across a series of experiential launch activations and partner events supporting Candy Crush product campaigns and brand collaborations.',
      'Delivered with King and Jack Morton Worldwide, the programme included immersive public environments, large-scale branded installations and audience-focused entertainment experiences designed to drive visibility, participation and social engagement.',
      'Projects ranged from the Candy Crush Castle takeover through to partner activations at the Grammy Awards and Coachella, integrating live performance, public interaction and large-format experiential design.',
    ],
    tags: ['Experiential Marketing', 'Immersive Activations', 'Branded Entertainment', 'Public Engagement', 'Pop-Up Experiences', 'Live Event Production', 'Consumer Experience'],
    images: [
      { src: 'assets/experience/candy.jpg' },
      { type: 'video', src: 'assets/experience/videos/candy-crush-soda.mp4', poster: 'assets/experience/candy.jpg' },
      { src: 'assets/experience/candy-2.jpg' },
      { src: 'assets/experience/candy-3.jpg' },
      { src: 'assets/experience/candy-4.jpg' },
      { src: 'assets/experience/candy-5.webp' },
      { src: 'assets/experience/candy-6.jpg' },
      { src: 'assets/experience/candy-7.jpg' },
      { src: 'assets/experience/candy-8.jpg' },
      { src: 'assets/experience/candy-9.jpg' },
      { src: 'assets/experience/candy-10.jpeg' },
      { src: 'assets/experience/candy-11.jpg' },
    ],
  },
  {
    id: 'virgin-bolt',
    title: 'Virgin Media · Usain Bolt',
    label: 'Thames Floating LED Spectacle',
    projectType: 'Engineering-Led Public Spectacle',
    client: 'Virgin Media',
    agency: 'Curb · Treatment Studio',
    role: 'Creative Producer',
    discipline: 'Brand Experience',
    year: '2016',
    disciplines: ['Live', 'Culture', 'Sport'],
    tagline: 'Landmark floating screen installation and public spectacle on the River Thames celebrating Virgin Media’s partnership with Usain Bolt.',
    outcome: 'A landmark experiential project combining engineering, marine operations and live public spectacle — demonstrating how large-scale experiential storytelling could be delivered through technically ambitious public installations within central London’s most visible civic environments.',
    scope: [
      'Experiential brand activations',
      'Large-scale public spectacle',
      'Engineering-led live events',
      'River and marine operations',
      'Public realm coordination',
      'Technical production',
      'Audience experience design',
      'Brand storytelling environments',
    ],
    body: [
      'Creative production for Virgin Media’s “Be The Fastest” activation featuring Olympic champion and world-record holder Usain Bolt.',
      'At the centre of the project was a 100-metre floating LED screen installed on the River Thames — the largest floating screen ever created at the time — requiring significant engineering coordination, marine operations and public authority approvals within central London.',
      'Guests gathered beside the London Eye to witness the arrival of the screen via the Thames before experiencing a specially commissioned film celebrating Usain Bolt and Virgin Media’s sponsorship programme.',
      'The activation combined large-scale experiential storytelling, live spectacle and complex technical delivery within one of London’s most visible public environments, integrating marine logistics, public realm coordination and live audience operations.',
    ],
    tags: ['Experiential Marketing', 'Public Spectacle', 'Live Experience', 'Technical Production', 'Engineering Integration', 'Public Realm Activation', 'Brand Experience', 'Marine Operations'],
    images: [
      { src: 'assets/experience/bolt-london-eye.jpg' },
      { type: 'video', src: 'assets/experience/videos/virgin-bolt.mp4', poster: 'assets/experience/bolt-london-eye.jpg' },
      { src: 'assets/experience/bolt-1.jpg' },
      { src: 'assets/experience/bolt-13.jpg' },
      { src: 'assets/experience/bolt-15.jpg' },
      { src: 'assets/experience/bolt-pic-1.jpg' },
      { src: 'assets/experience/bolt-pic-2.jpg' },
      { src: 'assets/experience/bolt-pic-3.jpg' },
      { src: 'assets/experience/bolt-pic-4.jpg' },
      { src: 'assets/experience/bolt-pic-5.jpg' },
      { src: 'assets/experience/bolt-btf-1.jpg' },
      { src: 'assets/experience/bolt-btf-2.jpg' },
      { src: 'assets/experience/bolt-btf-4.jpg' },
    ],
  },
  {
    id: 'santander',
    title: 'The Numbers Game',
    label: 'National Education & Football Roadshow',
    projectType: 'National Educational Touring Programme',
    client: 'Santander',
    agency: null,
    role: 'Executive Producer',
    discipline: 'Brand Experience',
    year: '2017',
    disciplines: ['Live', 'Sport'],
    tagline: 'Award-winning national roadshow using football culture and live participation to promote numeracy and learning.',
    outcome: 'A large-scale public engagement programme using sport and experiential participation to support education and community learning — demonstrating how touring sponsorship platforms could be used to create meaningful educational impact and socially driven audience experiences.',
    scope: [
      'National touring roadshows',
      'Educational engagement programmes',
      'Schools participation initiatives',
      'Sports sponsorship activation',
      'Public participation experiences',
      'Interactive learning environments',
      'Community engagement',
      'Experiential marketing',
    ],
    body: [
      'Executive production for Santander’s “The Numbers Game” — an award-winning national roadshow developed through Santander’s UEFA Champions League sponsorship programme.',
      'Touring across 20 towns and cities throughout the UK, the programme combined inflatable football activities, digital interactives, quizzes and live participation experiences designed to promote numeracy through football culture and audience engagement.',
      'Alongside the public roadshow, the programme delivered a dedicated schools engagement initiative featuring learning-focused challenges and educational activities linked to further numeracy development and classroom learning outcomes.',
      'The activation demonstrated how large-scale experiential roadshows and sports sponsorship platforms could be used to create meaningful public engagement, educational participation and socially driven audience experiences.',
    ],
    tags: ['Educational Engagement', 'Touring Activations', 'Public Participation', 'Sports Sponsorship', 'Experiential Learning', 'Community Engagement', 'Audience Interaction', 'Roadshow Production'],
    images: [
      { src: 'assets/experience/santander-hero.jpg' },
      { src: 'assets/experience/santander-cardiff-22.jpg' },
      { src: 'assets/experience/santander-cardiff-42.jpg' },
      { src: 'assets/experience/santander-cardiff-53.jpg' },
      { src: 'assets/experience/santander-cardiff-101.jpg' },
      { src: 'assets/experience/santander-cardiff-145.jpg' },
      { src: 'assets/experience/santander-57.jpg' },
      { src: 'assets/experience/santander-59.jpg' },
      { src: 'assets/experience/santander-120.jpg' },
      { src: 'assets/experience/santander-139.jpg' },
      { src: 'assets/experience/santander-157.jpg' },
      { src: 'assets/experience/santander-f2-003.jpg' },
      { src: 'assets/experience/santander-f2-135.jpg' },
      { src: 'assets/experience/santander-img-7763.jpg' },
      { src: 'assets/experience/santander-img-7837.jpg' },
    ],
  },
  {
    id: 'car-free-day',
    title: 'Car Free Day London',
    label: 'City-Wide Public Realm Programme',
    projectType: 'Civic Participation Event',
    client: 'Mayor of London & TfL',
    agency: 'WRG',
    role: 'Executive Producer',
    discipline: 'Public Event',
    year: '2019',
    disciplines: ['Public Event', 'Public Realm', 'Culture'],
    tagline: 'City-wide public realm programme temporarily transforming central London into a large-scale pedestrian and cycling environment.',
    outcome: 'A people-first civic event reclaiming central London streets through culture, movement and public participation — opening the city to pedestrians, cyclists and community life within one of Europe’s busiest urban environments.',
    scope: [
      'Civic participation events',
      'Public realm activation',
      'City-wide audience operations',
      'Community engagement',
      'Cultural programming',
      'Live event infrastructure',
      'Stakeholder coordination',
      'Urban public events',
    ],
    body: [
      'Executive production for the Mayor of London and TfL’s Car Free Day — a city-wide public realm programme temporarily transforming central London streets into spaces for cycling, culture and public participation.',
      'Delivered across central London, the programme combined live performance, cultural activity, cycling initiatives and family-focused public engagement experiences within traffic-free environments reclaimed for public use.',
      'The event encouraged audiences to experience London differently by opening major streets and civic spaces to pedestrians, cyclists and community participation while integrating large-scale public operations, city stakeholder coordination and live event infrastructure.',
      'Operating within one of Europe’s busiest urban environments required extensive coordination across local authorities, transport stakeholders, public agencies and operational partners while maintaining safe and accessible public audience environments.',
    ],
    tags: ['Civic Events', 'Public Realm', 'Community Engagement', 'Urban Activation', 'City Programming', 'Public Participation', 'Cycling Culture', 'Large-Scale Events'],
    images: [
      { src: 'assets/experience/cfd-1-bikes.jpg' },
      { src: 'assets/experience/cfd-2-yoga-bridge.jpg' },
      { src: 'assets/experience/cfd-3-yoga-square.jpg' },
      { src: 'assets/experience/cfd-4-runners.jpg' },
      { src: 'assets/experience/cfd-5-performer.jpg' },
      { src: 'assets/experience/cfd-6-swing.jpg' },
      { src: 'assets/experience/cfd-7-bank.webp' },
      { src: 'assets/experience/cfd-8-regent.webp' },
    ],
  },
];

Object.assign(window, { EXPERIENCE_DISCIPLINES: DISCIPLINES, EXPERIENCE_FEATURED: FEATURED, EXPERIENCE_ARCHIVE: ARCHIVE });
